export default [
      {
        id:1,
        tag:'aa',
        name:'招牌菜',
        icon:'',
        dishs:[
          {
            id:1,
            price:16,
            name:'蛋炒饭',
            sales:34,
            pic:'dish-1.jpg'
          },
          {
            id:2,
            price:10,
            name:'水果沙拉',
            sales:12,
            pic:'dish-2.jpg'
          }
        ]
      },
      {
        id:2,
        tag:'bb',
        name:'小吃类',
        icon:'',
                dishs:[
          {
            id:1,
            price:16,
            name:'蛋炒饭',
            sales:34,
            pic:'dish-1.jpg'
          },
          {
            id:2,
            price:10,
            name:'水果沙拉',
            sales:12,
            pic:'dish-2.jpg'
          }
        ]
      },
      {
        id:3,
        tag:'cc',
        name:'汤羹',
        icon:'',
                dishs:[
          {
            id:1,
            price:16,
            name:'蛋炒饭',
            sales:34,
            pic:'dish-1.jpg'
          },
          {
            id:2,
            price:10,
            name:'水果沙拉',
            sales:12,
            pic:'dish-2.jpg'
          }
        ]
      },
      {
        id:4,
        tag:'dd',
        name:'香锅',
        icon:'',
                dishs:[
          {
            id:1,
            price:16,
            name:'蛋炒饭',
            sales:34,
            pic:'dish-1.jpg'
          },
          {
            id:2,
            price:10,
            name:'水果沙拉',
            sales:12,
            pic:'dish-2.jpg'
          }
        ]
      },
      {
        id:5,
        name:'套餐',
        icon:'',
                dishs:[
          {
            id:1,
            price:16,
            name:'蛋炒饭',
            sales:34,
            pic:'dish-1.jpg'
          },
          {
            id:2,
            price:10,
            name:'水果沙拉',
            sales:12,
            pic:'dish-2.jpg'
          }
        ]
      }
    ]