module.exports = {
    players: [{
        name: "扎姆斯螺旋",
        avatar: "../../images/avatars/1204851.gif"
    }, {
        name: "大胖子",
        avatar: "../../images/avatars/1204854.gif"
    }, {
        name: "狮子男",
        avatar: "../../images/avatars/1204860.gif"
    }, {
        name: "理工男",
        avatar: "../../images/avatars/1204861.gif"
    }, {
        name: "樱木花道",
        avatar: "../../images/avatars/1204862.gif"
    }, {
        name: "查尔斯",
        avatar: "../../images/avatars/1204863.gif"
    }, {
        name: "卷发",
        avatar: "../../images/avatars/1204864.gif"
    }, {
        name: "突突",
        avatar: "../../images/avatars/1204865.gif"
    }, {
        name: "大麻花",
        avatar: "../../images/avatars/1204868.gif"
    }, {
        name: "双马尾",
        avatar: "../../images/avatars/1204873.gif"
    }, {
        name: "简单女孩",
        avatar: "../../images/avatars/1204887.gif"
    }, {
        name: "来自星星的你",
        avatar: "../../images/avatars/1204888.gif"
    }, {
        name: "童言",
        avatar: "../../images/avatars/1204889.gif"
    }, {
        name: "小花朵",
        avatar: "../../images/avatars/1204890.gif"
    }, {
        name: "扶桑花女孩",
        avatar: "../../images/avatars/1204891.gif"
    }, {
        name: "萝莉",
        avatar: "../../images/avatars/1204892.gif"
    }, {
        name: "大姑娘",
        avatar: "../../images/avatars/1204893.gif"
    }, {
        name: "向往阳光",
        avatar: "../../images/avatars/1204894.gif"
    }]
};