Page({
    data:{
        status:true,
        userInfo:{},
        focus:false,
        pk:[
            {
                title:'新国标GB1589你支持吗？',
                likeText:'支持',
                likeTotal:322941,
                unlikeText:'反对',
                unlikeTotal:322941,
                percent:30
            },
            {
                title:'6轴半挂车，你支持总重多少吨？',
                likeText:'49吨',
                likeTotal:322941,
                unlikeText:'55吨',
                unlikeTotal:322941,
                percent:40
            },
            {
                title:'双导6X2牵引车，你支持总重多少吨？',
                likeText:'46吨',
                likeTotal:322941,
                unlikeText:'49吨',
                unlikeTotal:322941,
                percent:50
            }
        ],
        comments:{
            title:'更多网友问题集锦',
            list:[
                {
                    avatar:'http://face.360che.com/data/avatar/new/63/b812b9e73eadbe1977ac8bea49f1c461_big.jpg',
                    userName:'你明白就够了',
                    content:'这这里说在多都没用同志们省省口舌吧！我都有一万个操，',
                    pid:'4779',
                    date:'8分钟前'
                },
                {
                    avatar:'http://wx.qlogo.cn/mmopen/NVpBSZOmzfp83mFtnfXKqBGYic8WJ8gGmib2yX5iaPqIOPt5b5zWy6eTic47q6DGQgqyR2icJaGJQQBa76hvibT1GkNfwuMicGKoibJJ/0',
                    userName:'静坐常思自己过',
                    content:'六轴多会能统一49吨，',
                    pid:'4778',
                    date:'8分钟前'
                },
                {
                    avatar:'http://face.360che.com/data/avatar/new/63/b812b9e73eadbe1977ac8bea49f1c461_big.jpg',
                    userName:'你明白就够了',
                    content:'我都以经看不到希望了，说得不超四十九，高不超四米，现在又可以装四米五，国家政策是用来给他们玩得，',
                    pid:'4777',
                    date:'9分钟前'
                },
                {
                    avatar:'http://wx.qlogo.cn/mmopen/ibFxI4hlxYLM4GWstYzlZHZ4OScoAH4QHApaAVMfiaDuQDCibmO2NA5ckvlKv7Svcfytud2IKQEBuKKBEz6VU5POdaULywciaklh/0',
                    userName:'張維慶',
                    content:'好烦好烦好烦好烦',
                    borrow:{
                        userName:'顺仔888',
                        date:'1小时前',
                        content:'强烈要求交通部重新发布一下.，全国单双驱统一载重，现在全国各地不统一'
                    },
                    pid:'4776',
                    date:'28分钟前'
                },
                {
                    avatar:'http://face.360che.com/data/avatar/new/81/25b40c7f1e3a8919dc98c582730c91d6_big.jpg',
                    userName:'顺仔888',
                    content:'强烈要求交通部重新发布一下.，全国单双驱统一载重，现在全国各地不统一',
                    pid:'4775',
                    date:'1小时前'
                },
                {
                    avatar:'http://face.360che.com/data/avatar/new/81/25b40c7f1e3a8919dc98c582730c91d6_big.jpg',
                    userName:'顺仔888',
                    content:'双导双驱都应49吨',
                    pid:'4774',
                    date:'1小时前'
                },
                {
                    avatar:'http://wx.qlogo.cn/mmopen/Q3auHgzwzM608we4ygdOoMmibuq7iczWn7Vfsh9AN1l4XWEffKVmnZ3ibVJYBPBY35XtGRmbawz8mibm81UHdxYSNyTtBZ4N7OHaJa7ibGzmojZs/132',
                    userName:'以后的幸福045',
                    content:'双导向六轴车，限制重量是多少。',
                    pid:'4773',
                    date:'2小时前'
                },
                {
                    avatar:'http://wx.qlogo.cn/mmopen/BYPPjMCOic4RFE9u9PA38yCaxiawMKKqA7FItCrdQh6Jz0zwD91mPca5FP3CM5OBe1DYQoVnvNGwKFtR56mNlODzK09mGbic40ib/132',
                    userName:'霸道022',
                    content:'治超治超越治越超了，真是乱套啦！新规就是一个笑话',
                    pid:'4763',
                    date:'14小时前'
                },
                {
                    avatar:'http://wx.qlogo.cn/mmopen/BYPPjMCOic4RFE9u9PA38yCaxiawMKKqA7FItCrdQh6Jz0zwD91mPca5FP3CM5OBe1DYQoVnvNGwKFtR56mNlODzK09mGbic40ib/132',
                    userName:'霸道022',
                    content:'治超治超越治越超了，真是乱套啦！新规就是一个笑话',
                    pid:'4763',
                    date:'14小时前'
                },
                {
                    avatar:'http://wx.qlogo.cn/mmopen/BYPPjMCOic4RFE9u9PA38yCaxiawMKKqA7FItCrdQh6Jz0zwD91mPca5FP3CM5OBe1DYQoVnvNGwKFtR56mNlODzK09mGbic40ib/132',
                    userName:'霸道022',
                    content:'治超治超越治越超了，真是乱套啦！新规就是一个笑话',
                    pid:'4763',
                    date:'14小时前'
                }
            ]
        }
    },
    onLoad:function(){
        var me = this;
        wx.getUserInfo({
            success: function(res) {
                var userInfo = res.userInfo;
                me.setData({
                    userInfo:{
                        avatar:userInfo.avatarUrl,
                        name:userInfo.nickName
                    }
                })
            },
            fail:function(err){}
        })
    },
    showBox:function(){
        this.setData({
            status:false
        })
    },
    hideBox:function(e){
        this.setData({
            status:true
        })
    },
    preventDefault:function(e){
        console.log(e);
    }
})
