var app = getApp();
Page({
    data: {
        questions:[
            {
                position:1,
                link:'detail/detail?id=0',
                text:'GB1589对于半挂车的规定有哪些？'
            },
            {
                position:2,
                link:'detail/detail?id=1',
                text:'新政中对长头车市场的规定知多少？'
            },
            {
                position:3,
                link:'detail/detail?id=2',
                text:'GB1589对于轿运车市场有哪些影响？'
            },
            {
                position:4,
                link:'detail/detail?id=3',
                text:'GB1589对货车和挂车的宽度做出哪些改变？'
            },
            {
                position:5,
                link:'detail/detail?id=4',
                text:'不同轴数的车辆的最大允许总质量限值是多少？'
            },
            {
                position:6,
                link:'detail/detail?id=5',
                text:'在新版的GB1589对于货车列车有哪些规定？'
            }
        ]
    }
})
